In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
import pandas as pd

#data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AIML Dataset.csv')
data = pd.read_csv('/Users/cosmos/Documents/AIML Dataset.csv')
#data = pd.read_csv('/Users/cosmos/Documents/test-30.csv')

In [2]:
part_75 = data.sample(frac = 0.1)
part_75.to_csv('db.csv')

In [25]:
data['isFlaggedFraud'].unique()

array([0, 1])

In [2]:
data.head(3)

step      type   amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT  9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT  1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER   181.00  C1305486145          181.0            0.00   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0

DATA PRE PROCESSING

In [3]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

data['scaled_step'] = scaler.fit_transform(data['step'].values.reshape(-1,1))

In [4]:
data.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  \
0  M1979787155             0.0             0.0        0               0   
1  M2044282225             0.0             0.0        0               0   
2   C553264065             0.0             0.0        1               0   
3    C38997010         21182.0             0.0        1               0   
4  M1230701703             0.0             0.0        0               0   

   scaled_step  
0    -1.329609  
1    -1.329609  
2    -1.329609  
3    -1.329609  
4    -1.329609

In [5]:
columns =data.columns
columns1 = ['scaled_step','amount','oldbalanceOrg', 'newbalanceOrig','oldbalanceDest', 'newbalanceDest']


In [6]:
import os
import warnings
warnings.filterwarnings('ignore')
#Packages related to data importing, manipulation, exploratory data #analysis, data understanding
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from termcolor import colored as cl # text customization
#Packages related to data visualizaiton
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
#Setting plot sizes and type of plot
plt.rc("font", size=14)
plt.rcParams['axes.grid'] = True
plt.figure(figsize=(6,3))
plt.gray()
from matplotlib.backends.backend_pdf import PdfPages
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
from sklearn.impute import MissingIndicator, SimpleImputer
from sklearn.preprocessing import PolynomialFeatures, KBinsDiscretizer, FunctionTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer, OrdinalEncoder
# import statsmodels.formula.api as smf
# import statsmodels.tsa as tsa
from sklearn.linear_model import LogisticRegression, LinearRegression, ElasticNet, Lasso, Ridge
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_graphviz
from sklearn.ensemble import BaggingClassifier, BaggingRegressor,RandomForestClassifier,RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier,GradientBoostingRegressor, AdaBoostClassifier, AdaBoostRegressor
from sklearn.svm import LinearSVC, LinearSVR, SVC, SVR
#
# from xgboost import XGBClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xgboost as xgb
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.model_selection import train_test_split
from sklearn.metrics import average_precision_score
from xgboost.sklearn import XGBClassifier
from xgboost import plot_importance

<Figure size 432x216 with 0 Axes>

CUSTOM PIPELINE

In [17]:
# making a custom transformer

from sklearn.base import BaseEstimator, TransformerMixin

class CustomTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, Columns):
        self.Columns=Columns
        
    def fit(self,X,y=None):
        return self
    
    def transform(self,X):
        New_X=X.copy()
        New_X=New_X[self.Columns].copy()
        return New_X

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler #standirize values
from sklearn.impute import SimpleImputer #fill in missing values

#adding parameters
pipeline=Pipeline([
    ('custom_tr', CustomTransformer(columns1)),
    ('std_scaler',StandardScaler())
])

In [9]:
X = pipeline.fit_transform(data)
y = data['isFraud'].copy()

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [21]:
X_train

array([[-0.20654002,  0.0088095 ,  2.36713167,  2.39421532,  0.21872176,
         0.11812277],
       [-1.43606008, -0.06782964, -0.28871645, -0.29244171, -0.21192516,
        -0.19209018],
       [ 1.07216085, -0.24739849, -0.28871645, -0.29244171, -0.3238139 ,
        -0.33341141],
       ...,
       [ 0.12367394, -0.13254934, -0.28119825, -0.29244171,  2.45388906,
         2.26359423],
       [-0.38921157, -0.06521956, -0.25289886, -0.20902024,  0.13709915,
         0.05477527],
       [-0.53675398, -0.0813115 ,  4.14282798,  4.12955643, -0.25560683,
        -0.30589828]])

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model_lr = LinearRegression()
model_lr.fit(X_train,y_train)

predictions=model_lr.predict(X_test)
mse=mean_squared_error(y_test, predictions)
rmse=np.sqrt(mse)
rmse

0.034242446286376425

In [10]:
#label encoder
from sklearn import preprocessing
from sklearn import utils

lab_enc = preprocessing.LabelEncoder()
encoded =lab_enc.fit_transform(y_train.astype('int'))

In [26]:
#trying random forest algo

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


forest_reg=RandomForestClassifier()


x=forest_reg.fit(X_train,y_train)

In [27]:
from sklearn.metrics import classification_report

y_pred=x.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9994459833795014


In [28]:
y_test

149985     0
644664     0
423265     0
557990     0
3953       0
          ..
651285     0
1138227    0
240772     0
718313     0
193275     0
Name: isFraud, Length: 254505, dtype: int64

In [25]:
from sklearn.neural_network import MLPRegressor

clf = MLPRegressor(hidden_layer_sizes= (40,40,40), random_state=1, alpha =0.01,max_iter=1, warm_start=True)

licz= []
accu = []
loss =[]
test = []

for i in range(150):
    clf.fit(X_train,y_train)
    licz.append(i)
    accu.append(clf.score(X_train,y_train))
    loss.append(clf.loss_)
    test.append(clf.score(X= X_test,y = y_test))
    if i%10==0:
         print("iter",i,"\taccuracy",clf.score(X_train, y_train),"\test",clf.score(X= X_test,y = y_test),"\tloss",clf.loss_)

import matplotlib.pyplot as plt
print(clf.score(X= X_test,y = y_test))
plt.plot(licz[5:],accu[5:],test[5:])

iter 0 	accuracy 0.16571407133995342 	est 0.13985461419839773 	loss 0.0020416630066499267
iter 10 	accuracy 0.32081554872650686 	est 0.30002734101588424 	loss 0.0005484408056939574
iter 20 	accuracy 0.3376239361878357 	est 0.31737246570290933 	loss 0.000540402391906225
iter 30 	accuracy 0.3424124980549629 	est 0.3225861305737636 	loss 0.0005386620167553527


DecisionTreeClassifier

In [11]:
DT = DecisionTreeClassifier(max_depth = 4, criterion = 'entropy')
DT.fit(X_train, y_train)
dt_yhat = DT.predict(X_test)

In [15]:
print ('F1 score of the Decision Tree model is {}'. format (f1_score(y_test, dt_yhat)))

F1 score of the Decision Tree model is 0.4513274336283186


In [16]:
print('F1 score of the Decision Tree model is {}'.format(f1_score(y_test, dt_yhat)))


F1 score of the Decision Tree model is 0.4513274336283186


In [17]:
confusion_matrix(y_test, dt_yhat, labels = [0, 1])


array([[254155,      4],
       [   244,    102]])

KNN

In [36]:
n = 7
KNN = KNeighborsClassifier(n_neighbors = n)
KNN.fit(X_train, y_train)
knn_yhat = KNN.predict(X_test)

In [37]:
print('Accuracy score of the K-Nearest Neighbors model is {}'.format(accuracy_score(y_test, knn_yhat)))

Accuracy score of the K-Nearest Neighbors model is 0.9991120017288462


In [35]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_yhat = lr.predict(X_test)

print('Accuracy score of the Logistic Regression model is {}'.format(accuracy_score(y_test, lr_yhat)))

Accuracy score of the Logistic Regression model is 0.9990530637904953


In [32]:
svm = SVC()
svm.fit(X_train, y_train)
svm_yhat = svm.predict(X_test)

print('Accuracy score of the Support Vector Machines model is {}'.format(accuracy_score(y_test, svm_yhat)))

Accuracy score of the Support Vector Machines model is 0.9989862674603642


In [24]:
import pickle
pickle.dump(svm_yhat, open('svm-sample.sav','wb'))

In [12]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

XGBOOST

In [11]:
weights = (y==0).sum()/(1.0 *  (y==1).sum())

xgb_classifier1 = XGBClassifier(max_depth = 3, scale_pos_weight = weights, n_jobs = 4)
xgb_prediction1 = xgb_classifier1.fit(X_train, y_train).predict_proba(X_test)



[12:25:54] WARNING: /private/var/folders/2h/lw5rv90j0ln7v084d1vkrcg80000gn/T/pip-install-l80c8wob/xgboost_fef350fccbfe489b99be0e26506efa00/build/temp.macosx-11.0-arm64-3.9/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [41]:
X_test.shape

(5726358, 6)

In [47]:
arr = np.array([ 0.7208694 , -0.28008524,  1.63042999,  1.60687384, -0.19406322, -0.21629092])
arr.shape

(6,)

In [44]:
xgb_classifier1.predict(arr)

XGBoostError: [13:53:21] /private/var/folders/2h/lw5rv90j0ln7v084d1vkrcg80000gn/T/pip-install-l80c8wob/xgboost_fef350fccbfe489b99be0e26506efa00/build/temp.macosx-11.0-arm64-3.9/xgboost/src/predictor/cpu_predictor.cc:341: Check failed: m->NumColumns() == model.learner_model_param->num_feature (1 vs. 6) : Number of columns in data must equal to trained model.
Stack trace:
  [bt] (0) 1   libxgboost.dylib                    0x000000010af9631c dmlc::LogMessageFatal::~LogMessageFatal() + 124
  [bt] (1) 2   libxgboost.dylib                    0x000000010b07e57c void xgboost::predictor::CPUPredictor::DispatchedInplacePredict<xgboost::data::ArrayAdapter, 64ul>(dmlc::any const&, std::__1::shared_ptr<xgboost::DMatrix>, xgboost::gbm::GBTreeModel const&, float, xgboost::PredictionCacheEntry*, unsigned int, unsigned int) const + 356
  [bt] (2) 3   libxgboost.dylib                    0x000000010b07aebc xgboost::predictor::CPUPredictor::InplacePredict(dmlc::any const&, std::__1::shared_ptr<xgboost::DMatrix>, xgboost::gbm::GBTreeModel const&, float, xgboost::PredictionCacheEntry*, unsigned int, unsigned int) const + 440
  [bt] (3) 4   libxgboost.dylib                    0x000000010b011eb4 xgboost::gbm::GBTree::InplacePredict(dmlc::any const&, std::__1::shared_ptr<xgboost::DMatrix>, float, xgboost::PredictionCacheEntry*, unsigned int, unsigned int) const + 816
  [bt] (4) 5   libxgboost.dylib                    0x000000010b025994 xgboost::LearnerImpl::InplacePredict(dmlc::any const&, std::__1::shared_ptr<xgboost::DMatrix>, xgboost::PredictionType, float, xgboost::HostDeviceVector<float>**, unsigned int, unsigned int) + 160
  [bt] (5) 6   libxgboost.dylib                    0x000000010af8ebd4 void InplacePredictImpl<xgboost::data::ArrayAdapter>(std::__1::shared_ptr<xgboost::data::ArrayAdapter>, std::__1::shared_ptr<xgboost::DMatrix>, char const*, xgboost::Learner*, unsigned long, unsigned long, unsigned long long const**, unsigned long long*, float const**) + 768
  [bt] (6) 7   libxgboost.dylib                    0x000000010af8e5bc XGBoosterPredictFromDense + 300
  [bt] (7) 8   libffi.8.dylib                      0x00000001011e404c ffi_call_SYSV + 76
  [bt] (8) 9   libffi.8.dylib                      0x00000001011e174c ffi_call_int + 1208



In [12]:
print('AUPRC = {}'.format(average_precision_score(y_test, xgb_prediction1[:,1])))

AUPRC = 0.8863264036286873


In [30]:
y_test

4801897    0
2779475    0
784465     0
5635648    0
301298     0
          ..
1005529    0
5752325    0
3497273    0
1041449    0
2579418    0
Name: isFlaggedFraud, Length: 5726358, dtype: int64

In [33]:
import pickle
#pickle.dump(xgb_prediction1, open('xgboost-full.sav','wb'))
loaded_model = pickle.load(open('/Users/cosmos/Desktop/I-ll_think_about_it_later/models/xgboost-full.sav', 'rb'))


PREDICTIVE FUNCTION

In [34]:
result = loaded_model.predict(X_test)
print(result)

AttributeError: 'numpy.ndarray' object has no attribute 'predict'

In [19]:
print('AUPRC = {}'.format(average_precision_score(y_test, xgb_prediction1[:,1])))

NameError: name 'xgb_prediction1' is not defined